### ISSUE TITLE
Additional Steps to Install

### ISSUE THREAD

**Issue by kumarharsh** [pyros2097/moodle-playlyfe#1]
1. Install php5 and php5-curl on your system:

`sudo apt-get install php5 curl libcurl3 libcurl3-dev php5-curl php5-mcrypt`
1. Install composer
   `curl -sS https://getcomposer.org/installer | php`
   `mv composer.phar /usr/local/bin/composer`
2. Run `composer install`

**Comment by ghost** [comment]
Yeah.. i'll add a readme..
